# Generated by Django 4.2.7 on 2023-11-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.IntegerField(choices=[(1, 'Cliente'), (2, 'Colaborador')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=False)),
                ('person', models.ManyToManyField(to='tasks.person')),
            ],
        ),
    ]
